version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - ecommerce-network
    environment:
      - NODE_ENV=development
      - VITE_PRODUCT_SERVICE_URL=http://product-service:3000
      - VITE_AUTH_SERVICE_URL=http://auth-service:3001
      - VITE_ORDER_SERVICE_URL=http://order-service:3002

  product-service:
    build: ./services/product-service
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce
    #command: sh -c "./init-products.sh"

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    networks:
      - ecommerce-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3002"
    networks:
      - ecommerce-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce

  mongo:
    image: mongo:4.4.24-focal
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongo-data:
