services:
  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network

  product-service:
    build: ./services/product-service
    ports:
      - "3000:3000"
    networks:
      - ecommerce-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    networks:
      - ecommerce-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce

  order-service:
    build: ./services/order-service
    ports:
      - "3002:3002"
    networks:
      - ecommerce-network
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      - MONGODB_USER=mongo
      - MONGODB_PASSWORD=mongo
      - MONGODB_DATABASE=ecommerce
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge